version: '3'

services:
  web:
    build: ./server
    restart: always
    environment:
      FLASK_APP: "images_app"
    expose:
      - 8001
    volumes:
      - ./server:/server
      - images:/server/images/

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - images:/server/images/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  images: